version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: qwbsogxc
      POSTGRES_PASSWORD: 5qlmwDfExUpnRkkSOdfMP0_wX0o6g88g
      POSTGRES_DB: qwbsogxc
    ports:
      - "5432:5432"
    networks:
      - webnet

  spring:
    build: ./Back
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/qwbsogxc
      SPRING_DATASOURCE_USERNAME: qwbsogxc
      SPRING_DATASOURCE_PASSWORD: 5qlmwDfExUpnRkkSOdfMP0_wX0o6g88g
    networks:
      - webnet

  angular:
    build: ./Front
    ports:
      - "4200:4200"
    depends_on:
      - spring
    networks:
      - webnet

networks:
  webnet:
