version: '3'
services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - backend
